const XLSX = require('xlsx');
const wb = XLSX.readFile('August Master.xlsx');
const sheet = wb.Sheets['400'];
const data = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' });
console.log("Total Rows:", data.length);
console.log("--- Row 0 ---");
console.log(data[0]);
console.log("--- Row 1 ---");
console.log(data[1]);
console.log("--- Row 2 ---");
console.log(data[2]);
