// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { parseRideCo, parseRideCoSheets, parseRideCoWithReport } from '../utils/parsers/csvParsers';

const makeRideCoRows = (): Array<Array<string | number>> => {
  const rows = Array.from({ length: 20 }, () => Array<string | number>(4).fill(''));

  rows[9] = ['', 'Example', 'Shift1', 'Shift2'];
  rows[10] = ['Day', 'All Weekdays', 'All Weekdays', 'Sat'];
  rows[13] = ['Driver (optional)', 'John', 'North', 'South'];
  rows[14] = ['Shift Label', 'example', 'Bus 1A', 'Bus 1B'];
  rows[15] = ['Service Start Time', '9:00 AM', 0.25, 0.59375]; // 6:00, 14:15
  rows[16] = ['Service End Time', '5:00 PM', 0.5555555555555556, 1]; // 13:20, midnight
  rows[17] = ['Break 1 Window Start Time', '11:00 AM', 0.4166666666666667, 0.7916666666666666]; // 10:00, 19:00
  rows[18] = ['Break 1 Window End Time', '11:30 AM', 0.4409722222222222, 0.8159722222222222]; // 10:35, 19:35
  rows[19] = ['Break 1 Duration (min)', 15, '', ''];

  return rows;
};

describe('RideCo shift parser', () => {
  it('parses Excel numeric time fractions as times of day', () => {
    const shifts = parseRideCo(makeRideCoRows());

    expect(shifts).toHaveLength(2);
    expect(shifts[0]).toMatchObject({
      driverName: 'Bus 1A',
      zone: 'North',
      startSlot: 72, // 6:00 on 5-minute grid
      endSlot: 160, // 13:20
      breakStartSlot: 120, // 10:00
      breakDurationSlots: 7, // 35 minutes
      dayType: 'Weekday',
    });
  });

  it('treats Excel numeric midnight as next-day end when it is after the shift start', () => {
    const shifts = parseRideCo(makeRideCoRows());

    expect(shifts[1]).toMatchObject({
      driverName: 'Bus 1B',
      zone: 'South',
      startSlot: 171, // 14:15
      endSlot: 288, // 24:00 / next-day midnight
      breakStartSlot: 228, // 19:00
      breakDurationSlots: 7, // 35 minutes
      dayType: 'Saturday',
    });
  });

  it('finds the RideCo table when template rows move down', () => {
    const shiftedRows = [
      ['Cover sheet export'],
      ['Generated by RideCo'],
      [''],
      ...makeRideCoRows(),
    ];

    const shifts = parseRideCo(shiftedRows);

    expect(shifts).toHaveLength(2);
    expect(shifts[0]).toMatchObject({
      driverName: 'Bus 1A',
      zone: 'North',
      startSlot: 72,
    });
  });

  it('handles quoted CSV cells before the shift table', () => {
    const csv = [
      '"Explanation, with comma",,,,,',
      '"Another ""quoted"" note",,,,,',
      ',Example,Shift1',
      'Day,All Weekdays,All Weekdays',
      'Fleet,Ford Transit 450,',
      'Vehicle (optional),D-1434,',
      'Driver (optional),John,South',
      'Shift Label,example,"Bus, 20"',
      'Service Start Time,9:00 AM,6:30',
      'Service End Time,5:00 PM,14:30',
      'Break 1 Window Start Time,11:00 AM,N/B',
      'Break 1 Window End Time,11:30 AM,N/B',
      'Break 1 Duration (min),15,0',
    ].join('\n');

    const shifts = parseRideCo(csv);

    expect(shifts).toHaveLength(1);
    expect(shifts[0]).toMatchObject({
      driverName: 'Bus, 20',
      zone: 'South',
      startSlot: 78,
      endSlot: 174,
      breakDurationSlots: 0,
    });
  });

  it('chooses the workbook sheet that contains shift rows', () => {
    const shifts = parseRideCoSheets([
      [['Instructions'], ['No shifts here']],
      makeRideCoRows(),
    ]);

    expect(shifts).toHaveLength(2);
    expect(shifts[0].driverName).toBe('Bus 1A');
  });

  it('returns diagnostics for skipped shift columns', () => {
    const rows = makeRideCoRows();
    rows[9][4] = 'Shift3';
    rows[10][4] = 'Sun';
    rows[13][4] = 'North';
    rows[14][4] = 'Bus Missing Time';
    rows[15][4] = '';
    rows[16][4] = '14:00';

    const result = parseRideCoWithReport(rows, { sourceName: 'bad-template.csv' });

    expect(result.shifts).toHaveLength(2);
    expect(result.report.sourceName).toBe('bad-template.csv');
    expect(result.report.countsByDay).toEqual({
      Weekday: 1,
      Saturday: 1,
      Sunday: 0,
    });
    expect(result.report.skippedColumns).toEqual([
      expect.objectContaining({
        columnLabel: 'E',
        shiftHeader: 'Shift3',
        reason: 'Missing service start or end time.',
      }),
    ]);
  });
});
