import { describe, expect, it } from 'vitest';
import { createSyntheticProject, executeCommand, freezeBaseline, createAlternative } from '../utils/street-design-studio/domain';
import { compileScenario, localToLonLat, lonLatToLocal } from '../utils/street-design-studio/geometry';
import { makeSheet } from '../utils/street-design-studio/export';
import { parseReferenceGeoJson } from '../utils/street-design-studio/import';
import { validateImageryTemplate } from '../utils/street-design-studio/sources';

const area = (ring: [number, number][]) => Math.abs(ring.reduce((sum, p, i) => { const q = ring[(i + 1) % ring.length]; return sum + p[0] * q[1] - q[0] * p[1]; }, 0)) / 2;
describe('Street Design Studio geometry and commands', () => {
  it('compiles a 160 m by 17.2 m synthetic envelope with shared band boundaries', () => { const p = createSyntheticProject(), scene = compileScenario(p.existing); expect(area(scene.envelope)).toBeCloseTo(2752, 6); expect(scene.boundaries['left-b2']).toBe(scene.boundaries[p.existing.bands[2].innerBoundaryId]); expect(scene.dimensions[0].metres).toBeCloseTo(2.4, 6); });
  it('keeps the locked budget and last valid design after invalid direct width edit', () => { const p = createSyntheticProject(); expect(() => executeCommand(p, { type: 'width', scenarioId: 'existing', bandId: 'left-sidewalk', metres: 2.5 })).toThrow(/width budget conflict/); expect(p.existing.bands.find(b => b.id === 'left-sidewalk')?.width.metres).toBe(2); });
  it('atomically transfers width and keeps attachments aligned to a moved curb', () => { const p = createSyntheticProject(), before = compileScenario(p.existing).objects.find(o => o.id === 'stop-1')!.point; const next = executeCommand(p, { type: 'reallocate', scenarioId: 'existing', donorId: 'left-parking', recipientId: 'left-sidewalk', metres: 0.5 }); const after = compileScenario(next.existing).objects.find(o => o.id === 'stop-1')!.point; expect(next.existing.bands.filter(b => b.side === 'left').reduce((n,b) => n + b.width.metres, 0)).toBeCloseTo(8.6); expect(Math.hypot(after[0]-before[0],after[1]-before[1])).toBeCloseTo(0.5); expect(compileScenario(next.existing).dimensions[0].metres).toBeCloseTo(1.9); });
  it('replaces parking while preserving its outer boundary', () => { const p = createSyntheticProject(), old = compileScenario(p.existing).boundaries['left-b2']; const next = executeCommand(p, { type: 'replaceParking', scenarioId: 'existing', bandId: 'left-parking' }); expect(compileScenario(next.existing).boundaries['left-b2']).toEqual(old); expect(next.existing.bands.find(b => b.id === 'left-parking-cycle')?.width.metres).toBeCloseTo(1.8); });
  it('pins a deep baseline and blocks orphaned attachments', () => { const p = freezeBaseline(createSyntheticProject(), 'baseline-1', '2026-09-25T00:00:00Z'); const alt = createAlternative(p, 'alternative-1'); const hash = JSON.stringify(alt.baselines[0].scenario); const changed = executeCommand(alt, { type: 'replaceParking', scenarioId: 'alternative-1', bandId: 'left-parking' }); expect(JSON.stringify(changed.baselines[0].scenario)).toBe(hash); expect(() => executeCommand(changed, { type: 'alignment', scenarioId: 'alternative-1', points: [{ id: 'a', point: [0,0] }, { id: 'b', point: [90,0] }] })).toThrow(/orphaned|range/); });
  it('round-trips local projected points and writes a vector A3 sheet at an honest fixed scale', () => { const p = createSyntheticProject(), point: [number,number] = [100,8]; const back = lonLatToLocal(p, localToLonLat(p, point)); expect(Math.hypot(back[0]-point[0],back[1]-point[1])).toBeLessThan(0.001); const sheet = makeSheet(p,p.existing,500); expect(sheet.svg).toContain('<path'); expect(sheet.svg).toContain('CONCEPT DESIGN'); expect(sheet.widthMm).toBe(420); expect(100 * 1000 / sheet.scale).toBe(200); expect(() => makeSheet(p,p.existing,200)).toThrow(/does not fit/); });
  it('evaluates a gentle fillet and rejects a self-crossing alignment before commit', () => { const p = createSyntheticProject(); const curved = executeCommand(p, { type: 'alignment', scenarioId: 'existing', points: [{ id: 'a', point: [0,0] }, { id: 'b', point: [80,0], radius: 70 }, { id: 'c', point: [160,20] }] }); const compiled = compileScenario(curved.existing); expect(compiled.samples.length).toBeGreaterThan(3); expect(compiled.length).toBeGreaterThan(160); expect(() => executeCommand(p, { type: 'alignment', scenarioId: 'existing', points: [{ id: 'a', point: [0,0] }, { id: 'b', point: [100,100] }, { id: 'c', point: [0,100] }, { id: 'd', point: [100,0] }] })).toThrow(/self-cross/); });
  it('imports WGS84 reference polygons with holes but rejects unsupported geometry', () => { const p = createSyntheticProject(); const polygon = { type: 'FeatureCollection', features: [{ type: 'Feature', geometry: { type: 'Polygon', coordinates: [[[-79.7,44.4],[-79.699,44.4],[-79.699,44.401],[-79.7,44.4]], [[-79.6998,44.4001],[-79.6997,44.4001],[-79.6997,44.4002],[-79.6998,44.4001]]] }, properties: {} }] }; const parsed = parseReferenceGeoJson(p,JSON.stringify(polygon),'Test file'); expect((parsed.references[0].coordinates as [number,number][][]).length).toBe(2); expect(parsed.source.exportDerived).toBe('unknown'); expect(() => parseReferenceGeoJson(p, JSON.stringify({ type: 'FeatureCollection', features: [{ type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [] } }] }), 'bad')).toThrow(/unsupported/); });
  it('accepts only allowlisted HTTPS XYZ templates without query tokens', () => { expect(validateImageryTemplate('https://approved.example/{z}/{x}/{y}.png', ['approved.example'])).toContain('{z}'); expect(() => validateImageryTemplate('https://approved.example/{z}/{x}/{y}.png?key=secret', ['approved.example'])).toThrow(/approved/); });
  it('places an actual 100 m SVG edge at 200 mm on a 1:500 sheet', () => { const p = createSyntheticProject(); p.existing.alignment[1].point = [100,0]; p.existing.attachments = []; p.existing.dimensions = []; const svg = makeSheet(p,p.existing,500).svg; const edge = svg.match(/<path d="M([\d.]+) [\d.]+ L([\d.]+) [\d.]+/); expect(edge).not.toBeNull(); expect(Number(edge![2]) - Number(edge![1])).toBeCloseTo(200,3); });
  it('resizes the entire envelope only through an explicit metre command', () => { const p = createSyntheticProject(); const next = executeCommand(p, { type: 'resizeEnvelope', scenarioId: 'existing', totalMetres: 12 }); expect(next.existing.budgets.left + next.existing.budgets.right).toBeCloseTo(12); expect(next.existing.bands.find(b => b.id === 'left-travel')!.width.metres).toBeCloseTo(3.2 * 12 / 17.2); expect(p.existing.budgets.left + p.existing.budgets.right).toBeCloseTo(17.2); expect(() => executeCommand(p, { type: 'resizeEnvelope', scenarioId: 'existing', totalMetres: Number.NaN })).toThrow(/between 3 and 60/); });
});
