// Civic-address proposals approved by the manager on 2026-09-21 for the August report.
// Match exact normalized report aliases: do not broaden generic names to other branches.
// Building-level queries intentionally omit units; shared addresses do not merge entities.
export const APPROVED_SPECIALIZED_TRANSIT_ADDRESSES: ReadonlyArray<{
  label: string;
  address: string;
  sources: readonly string[];
}> = [
  {"label":"Ferris Place Dental / Medical","address":"85 Ferris Lane, Barrie, Ontario","sources":["https://www.mmcorp.ca/property.php?id=67"]},
  {"label":"Barrieview Retirement Communit","address":"3 Concert Way, Barrie, Ontario","sources":["https://www.aspiralife.ca/our-locations/ontario/barrie/aspira-the-barrieview-retirement-living/"]},
  {"label":"Amica Assisted Living","address":"70 Lakeside Terrace, Barrie, Ontario","sources":["https://brand.amica.ca/m/b68106ea1160e9ff/original/Guide-To-Senior-Living-In-Ontario-Amica-Tools-And-Resources.pdf","https://211ontario.ca/service/71089984/amica-little-lake-amica-little-lake/"]},
  {"label":"Eagle Ridge Medical - Front Do","address":"480 Huronia Road, Barrie, Ontario","sources":["https://www.sportsmedicine.on.ca/services/services.php","https://eagleridgepharmacy.ca/"]},
  {"label":"Peggy Hill Team Community Cent","address":"171 Mapleton Avenue, Barrie, Ontario","sources":["https://www.barrie.ca/community-recreation-environment/facilities-venues/peggy-hill-team-community-centre"]},
  {"label":"Scotiabank - Bayfield","address":"544 Bayfield Street, Barrie, Ontario","sources":["https://locator.scotiabank.com/advisors/business-advisor/chris.rook"]},
  {"label":"Swiss Chalet - Bayfield","address":"397 Bayfield Street, Barrie, Ontario","sources":["https://www.swisschalet.com/en/locations/on/barrie/397-bayfield-st"]},
  {"label":"City Hall","address":"70 Collier Street, Barrie, Ontario","sources":["https://www.barrie.ca/community-recreation-environment/community-events/family-day-celebrations"]},
  {"label":"Milestones Restaurant","address":"150 Park Place Boulevard, Barrie, Ontario","sources":["https://milestonesrestaurants.com/locations/barrie/"]},
  {"label":"Barrie Vascular Imaging","address":"60 Bell Farm Road, Barrie, Ontario","sources":["https://barrievascular.ca/","https://barrieveinclinic.com/wp-content/uploads/2024/01/barrie_vascular_2022_bw.pdf"]},
  {"label":"Brain Injury Services","address":"21 Essa Road, Barrie, Ontario","sources":["https://www.nsmhealthline.ca/displayservice.aspx?id=205141","https://www.trontario.org/files/Job-Postings/job-posting-bis-rehab-counsellor.pdf"]},
  {"label":"Eagle Ridge Medical - Back Doo","address":"480 Huronia Road, Barrie, Ontario","sources":["https://www.sportsmedicine.on.ca/services/services.php","https://eagleridgepharmacy.ca/"]},
  {"label":"Mandarin Restaurant","address":"28 Fairview Road, Barrie, Ontario","sources":["https://www.mandarinrestaurant.com/locations-old/barrie/"]},
  {"label":"One Eyed Jack Restaurant & Bar","address":"165 Wellington Street West, Barrie, Ontario","sources":["https://www.oneeyedjackpub.com/barrie"]},
  {"label":"Tim Hortons - Yonge at Maplevi","address":"837 Yonge Street, Barrie, Ontario","sources":["https://locations.timhortons.ca/fr/locations-list/on/barrie/"]},
  {"label":"Value Village ( Wellington Plaz","address":"165 Wellington Street West, Barrie, Ontario","sources":["https://stores.savers.com/on/barrie/valuevillage-thrift-store-2074.html"]},
  {"label":"Bob Rumball Center","address":"1 Royal Parkside Drive, Barrie, Ontario","sources":["https://www.bobrumball.org/wp-content/uploads/2024/04/Intro-TOC-for-Emerg-Plans-for-website-Mar-15_24-Final-20240410.pdf"]},
  {"label":"Heritage Square ( 94)","address":"94 Dean Avenue, Barrie, Ontario","sources":["https://ioof.com/uploads/files/1730379756_TERRACES-brochure-NEW.pdf"]},
  {"label":"Unique Minds Academy","address":"65 Cedar Pointe Drive, Barrie, Ontario","sources":["https://www.uniquemindsacademy.ca/contact-us.html"]},
  {"label":"Peggy Hill Team CC","address":"171 Mapleton Avenue, Barrie, Ontario","sources":["https://www.barrie.ca/community-recreation-environment/facilities-venues/peggy-hill-team-community-centre"]},
  {"label":"Westowne Dental","address":"420 Leacock Drive, Barrie, Ontario","sources":["https://www.westownedental.com/contact-us/"]},
  {"label":"Allandale Station Retirement R","address":"357 Yonge Street, Barrie, Ontario","sources":["https://chartwell.com/on/barrie/allandale-station"]},
  {"label":"Ardagh Family Dentistry | Best","address":"225 Ferndale Drive South, Barrie, Ontario","sources":["https://ardagh.ca/about-us/"]},
  {"label":"Barrie Denture Clinic","address":"34 Cedar Pointe Drive, Barrie, Ontario","sources":["https://barriedentureclinic.com/contact"]},
  {"label":"Bull & Barrel","address":"75 Cedar Pointe Drive, Barrie, Ontario","sources":["https://www.bullandbarrel.ca/event.php?id=38"]},
  {"label":"Canadian Blood Services","address":"231 Bayview Drive, Barrie, Ontario","sources":["https://sang.ca/index.php/en/blood/donor-centre-hours-locations"]},
  {"label":"Dollarama ( Springwater Marketp","address":"409 Bayfield Street, Barrie, Ontario","sources":["https://www.dollarama.com/fr-CA/localisateur/on/barrie-409-bayfield-st/"]},
  {"label":"Goodness Me","address":"79 Park Place Boulevard, Barrie, Ontario","sources":["https://goodnessme.ca/pages/storelocation"]},
  {"label":"Grove Park Home - Door on Cook","address":"234 Cook Street, Barrie, Ontario","sources":["https://www.groveparkhome.on.ca/about/our-team/grove-park-staff/"]},
  {"label":"NEW LIFE CHIRO","address":"320 Bayfield Street, Barrie, Ontario","sources":["https://booking.newlifechiro.ca/"]},
  {"label":"Victoria Village - Nursing Res","address":"78 Ross Street, Barrie, Ontario","sources":["https://victoriavillage.ca/contact/","https://www.ontario.ca/locations/longtermcare/homes/2914-victoria-village-manor/"]},
  {"label":"Will Dwyer Park","address":"81 Lakeshore Drive, Barrie, Ontario","sources":["https://agefriendlyactivities.simcoe.ca/events-archive/paws-for-a-cause-pet-walk-a-thon/"]},
  {"label":"Canadian Tire / Bayfield Mall","address":"320 Bayfield Street, Barrie, Ontario","sources":["https://www.barrie.ca/services-payments/garbage-recycling-organics/curbside-collection/garbage"]},
  {"label":"Centra Foods","address":"320 Bayfield Street, Barrie, Ontario","sources":["https://www.centrafoodmarket.com/"]},
  {"label":"Chuck's Roadhouse Bar & Grill","address":"407 Bayfield Street, Barrie, Ontario","sources":["https://chucksroadhouse.com/locations/barrie/"]},
  {"label":"Dunlop Billiards","address":"445 Dunlop Street West, Barrie, Ontario","sources":["https://www.wpbsa.com/gd-clubs/dunlop-billiards/","https://dunlop-billiards-sports-bar.barriedirect.ca/"]},
  {"label":"Northwest Barrie United Church","address":"464 Ferndale Drive North, Barrie, Ontario","sources":["https://www.nwbuc.ca/contact-us/"]},
  {"label":"Owen Hill Care Community ( LOC","address":"130 Owen Street, Barrie, Ontario","sources":["https://www.ontariohealthathome.ca/blobohahprod4cd80afe1b/wp-content/uploads/2026/02/NSM-LTC-Homes-List-and-Rates-EN.pdf"]},
  {"label":"Zehr's Market - Yonge","address":"620 Yonge Street, Barrie, Ontario","sources":["https://dis-prod.assetful.loblaw.ca/content/dam/loblaw-companies-limited/creative-assets/loblaw-ca/Ontario%20store%20list%20RATs.pdf","https://www.yellowpages.ca/bus/Ontario/Barrie/Zehrs/5903659.html"]},
  {"label":"Barrie Ocular Surgery","address":"441 Huronia Road, Barrie, Ontario","sources":["https://www.barrieocularsurgery.ca/"]},
  {"label":"Charity Bingo","address":"52 Bayfield Street, Barrie, Ontario","sources":["https://about.olg.ca/charitable-bingo-gaming/charitable-gaming-locations/","https://find-open.ca/barrie/barrie-charity-bingo-sponsors-association-801484"]},
  {"label":"Chef Chan","address":"190 Minet's Point Road, Barrie, Ontario","sources":["https://chefchanbarrie.com/"]},
  {"label":"Common Roof","address":"165 Ferris Lane, Barrie, Ontario","sources":["https://www.thecommonroof.ca/"]},
  {"label":"Eastview Secondary","address":"421 Grove Street East, Barrie, Ontario","sources":["https://eas.scdsb.on.ca/our_school/school_information"]},
  {"label":"Flashback Diner","address":"309 Bayfield Street, Barrie, Ontario","sources":["https://www.flashbackbreakfastandlunch.ca/"]},
  {"label":"Great Canadian Bagel ( Springwa","address":"411 Bayfield Street, Barrie, Ontario","sources":["https://greatcanadianbagel.com/store-locations/"]},
  {"label":"Home Depot","address":"10 Barrie View Drive, Barrie, Ontario","sources":["https://stores.homedepot.ca/on/barrie/home-improvement-barrie-on-7024.html"]},
  {"label":"Image Dental Laboratory","address":"33 Quarry Ridge Road, Barrie, Ontario","sources":["https://www.imagedentallaboratory.com/contact/"]},
  {"label":"Lakeshore Family Medicine","address":"11 Victoria Street, Barrie, Ontario","sources":["https://www.lakeshoremedicine.com/"]},
  {"label":"Leacock Plaza","address":"420 Leacock Drive, Barrie, Ontario","sources":["https://pub-barrie.escribemeetings.com/FileStream.ashx?DocumentId=11238"]},
  {"label":"Lodge Roberta Place","address":"489 Essa Road, Barrie, Ontario","sources":["https://www.jarlette.com/roberta-place-retirement-lodge/contact-us/"]},
  {"label":"Owen Hill Care Community","address":"130 Owen Street, Barrie, Ontario","sources":["https://siennaliving.ca/communities/owen-hill-community/"]},
  {"label":"Pet Valu ( Wellington Plaza)","address":"165 Wellington Street West, Barrie, Ontario","sources":["https://store.petvalu.ca/location/2382"]},
  {"label":"Service Canada","address":"48 Owen Street, Barrie, Ontario","sources":["https://offices.service.canada.ca/fr/Bureau/3582"]},
  {"label":"Sheba Shrine - John / Anne","address":"142 John Street, Barrie, Ontario","sources":["https://www.tourismbarrie.com/meet/choose-your-venue/conference-banquet-centres/traditions-at-sheba-shrine"]},
  {"label":"Swiss Chalet - Barrieview","address":"85 Barrie View Drive, Barrie, Ontario","sources":["https://www.swisschalet.com/en/locations/on/barrie/85-barrie-view-dr."]},
  {"label":"Winners - South - Park Place","address":"30 North Village Way, Barrie, Ontario","sources":["https://www.barrietoday.com/local-news/winners-set-to-open-new-location-at-park-place-2717125"]},
  {"label":"XPlay Amusements","address":"30 North Village Way, Barrie, Ontario","sources":["https://x-play.ca/contact/"]},
  {"label":"Eastview Secondary School","address":"421 Grove Street East, Barrie, Ontario","sources":["https://eas.scdsb.on.ca/our_school/school_information"]},
  {"label":"Farm Boy","address":"436 Bryne Drive, Barrie, Ontario","sources":["https://www.farmboy.ca/stores/barrie/"]},
  {"label":"Marks ( Park Place)","address":"80 Concert Way, Barrie, Ontario","sources":["https://www.marks.com/en/store-details/on/barrie-south-72.html"]},
  {"label":"MONTE CARLO INN","address":"81 Hart Drive, Barrie, Ontario","sources":["https://www.montecarloinns.com/barrie-suites/contact"]},
  {"label":"One Eyed Jack Restaurant &","address":"165 Wellington Street West, Barrie, Ontario","sources":["https://www.oneeyedjackpub.com/barrie"]},
  {"label":"Parkplace - Goodness Me","address":"79 Park Place Boulevard, Barrie, Ontario","sources":["https://goodnessme.ca/pages/storelocation"]},
  {"label":"Pharmasave ( Blake St)","address":"301 Blake Street, Barrie, Ontario","sources":["https://www.nsmhealthline.ca/displayService.aspx?id=203793"]},
  {"label":"Tim Hortons - Bayfield at Cun","address":"354 Bayfield Street, Barrie, Ontario","sources":["https://locations.timhortons.ca/fr/on/barrie/354-bayfield-st/","https://www.openinghours.ca/tim-hortons-354-bayfield-street-and-cundles-barrie-on"]},
  {"label":"TRUE COLOURS","address":"181 Livingstone Street East, Barrie, Ontario","sources":["https://www.truecolorsunisexsalon.ca/"]},
  {"label":"Wellington Plaza","address":"165 Wellington Street West, Barrie, Ontario","sources":["https://irp.cdn-website.com/29f2f584/files/uploaded/New%20Marketing%20Brochure-165%20Wellington%202.pdf"]},
  {"label":"West Bayfield Elementary Schoo","address":"49 Ford Street, Barrie, Ontario","sources":["https://wes.scdsb.on.ca/our_school/school_information"]},
  {"label":"Zehrs Market - Big Bay Pt","address":"620 Yonge Street, Barrie, Ontario","sources":["https://www.barrietoday.com/local-news/big-bay-point-zehrs-marks-grand-reopening-tuesday-4846700","https://www.specsavers.ca/stores/bigbaypoint"]},
];

// These 51 report labels remain for user review, even if a POI name matches.
export const SPECIALIZED_TRANSIT_MANUAL_REVIEW_LABELS: readonly string[] = [
  "Staples",
  "Great Clips Hair Salon",
  "Von Canada",
  "CMHA - Mental Health CNTR",
  "Royal Court Medical Ctr ( LOC)",
  "Cineplex Odeon",
  "150",
  "Budhist Temple",
  "KEMPENFEST STOP",
  "Life Labs",
  "Shoppers Drug Mart ( Bayfield)",
  "Roberta Place",
  "Bibles for Missions",
  "The UPS Store",
  "Kingdom Hall",
  "St. Vincent Park",
  "Barrie Foot Clinic",
  "Old Navy",
  "Simcoe Cnty Dist. Health Unit",
  "Springwater Plaza",
  "Camphill",
  "Free Methodist Church",
  "Starbucks",
  "Christian Horizons Group Home",
  "national bank",
  "Native Centre",
  "Royal Court Medical Ctr",
  "Shoppers Drug Mart ( North Barr",
  "Health Partners Professional",
  "Kenzington Burger Bar",
  "Kingdom Hall South",
  "Montana's Cookhouse Saloon",
  "Ovenden Bldg",
  "Shoppers drug mart ( Prince Wil",
  "Spirit Catcher",
  "Tim Hortons - Cundles - North",
  "Urban Grind Coffee Co",
  "Winners ( Springwater Marketpla",
  "Best Buy",
  "EUROPEAN FINE FOOD & DELI",
  "First Choice Hair",
  "Frescho Mapleview",
  "Giovanni & Perri",
  "Kelsey's Restaurant",
  "Mary Brown's ( Wellington Plaza",
  "Nights of Columbus",
  "Rexall",
  "Rogers",
  "Sobeys",
  "Value Village",
  "Wentworths Eatery,Cafe & Cater",
];
